require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "Gemfile"
    - "Rakefile"
    - "bin/**/*"
    - "storage/**/*"
    - "public/**/*"
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "tmp/**/*"

MethodLength:
  CountComments: true
  Max: 20
