require:
  - rubocop-rails

AllCops:
  Exclude:
    - "Gemfile"
    - "Rakefile"
    - "bin/**/*"
    - "storage/**/*"
    - "public/**/*"
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "tmp/**/*"
